# Generated by Django 3.1.1 on 2020-09-24 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.role'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
